### PR TITLE
refactor: uneject app

### PR DESCRIPTION
**Pull request by ismay**
To allow for easier merging of #49

- [x] Verify there are no missing dependencies (only `"sw-precache-webpack-plugin"` seems to differ from CRA dependencies, and CRA does bundle a service worker, so should be ok)
- [x] Make sure all test and CI steps succeed (was test-e2e working properly before? It doesn't now)
- [x] Test app still works correctly

Besides unejecting the app, I also cleaned up minor things I encountered whilst unejecting, like:

- Removing superfluous comments (comments that did not add extra information)
- Removed unnecessary whitespace (mainly between imports, made it more difficult to scan)
- Removed unnecessary `eslint-disable` (used more specific ones where needed)

### CODE REVIEW

**Comment by varl** [comment]
This would be a good opportunity to add `d2-style` as well.

**Comment by ismay** [comment]
Yeah definitely. I'm still not sure how we want to approach adding d2-style to repos though, since the discussion in https://github.com/dhis2/notes/issues/28 has stalled a bit.

**Comment by ismay** [comment]
If we want to do it I could do that in a separate pr. To not clutter up this one too much.

**Comment by varl** [comment]
Right. Similar to that.. Should we backport unejecting too?

**Comment by ismay** [comment]
To be honest, I'm leaning more and more towards not troubling ourselves with backporting unless _absolutely_ necessary. I'm noticing that it's this barrier for doing important maintenance on master. I'd rather have the backporting be hard and take more time, than postpone quality improvements on master. At least that way the true cost of backporting is also not hidden in all the work we do on master.

**Comment by varl** [comment]
Great, sounds good to me. I'd also rather reimplement a bug fix on an old branch than bother with automagic merges there are a massive conflicts.

**Pull request merged**
